name: build.yml

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13.7

      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --onefile export.py --collect-all pyfiglet --name "GCBE"
      - name: Release Linux Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/GCBE

  build-windows:
    name: Build Windows Exe
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13.7
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --onefile export.py --collect-all pyfiglet --name "GCBE"
      - name: Release Windows Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/GCBE.exe